#!/usr/bin/env bash
git clone git@github.com:sanchezcarlosjr/non-dominated-set-generator-cli.git
cd non-dominated-set-generator-cli
python3 -m venv venv
source venv/bin/activate
pip install wheel
cd publish
sh publish_local.sh
pip install -r developer_requirements.txt 
cd ..
source venv/bin/activate
echo "Ready! 🥳"
